Fix linting errors after upgrade to new 1.92 Rust version.
The following linting errors and warnings were fixed:

    error: manual implementation of `.is_multiple_of()`
       --> examples/macro_reference.rs:129:33
        |
    129 |                     set_active: counter.value % 2 == 0,
        |                                 ^^^^^^^^^^^^^^^^^^^^^^ help: replace with: `counter.value.is_multiple_of(2)`
        |
        = help: for further information visit https://rust-lang.github.io/rust-clippy/rust-1.92.0/index.html#manual_is_multiple_of
        = note: `-D clippy::manual-is-multiple-of` implied by `-D warnings`
        = help: to override `-D warnings` add `#[allow(clippy::manual_is_multiple_of)]`

    error: manual implementation of `.is_multiple_of()`
      --> examples/macro_reference.rs:79:29
       |
    79 |                 append = if counter.value % 2 == 0 {
       |                             ^^^^^^^^^^^^^^^^^^^^^^ help: replace with: `counter.value.is_multiple_of(2)`
       |
       = help: for further information visit https://rust-lang.github.io/rust-clippy/rust-1.92.0/index.html#manual_is_multiple_of

    error: manual implementation of `.is_multiple_of()`
      --> examples/macro_reference.rs:83:27
       |
    83 |                 } else if counter.value % 3 == 0 {
       |                           ^^^^^^^^^^^^^^^^^^^^^^ help: replace with: `counter.value.is_multiple_of(3)`
       |
       = help: for further information visit https://rust-lang.github.io/rust-clippy/rust-1.92.0/index.html#manual_is_multiple_of

    error: manual implementation of `.is_multiple_of()`
      --> examples/macro_reference.rs:71:33
       |
    71 |                         #[track(counter.value % 10 == 0)]
       |                                 ^^^^^^^^^^^^^^^^^^^^^^^ help: replace with: `counter.value.is_multiple_of(10)`
       |
       = help: for further information visit https://rust-lang.github.io/rust-clippy/rust-1.92.0/index.html#manual_is_multiple_of

    error: manual implementation of `.is_multiple_of()`
       --> examples/macro_reference.rs:129:33
        |
    129 |                     set_active: counter.value % 2 == 0,
        |                                 ^^^^^^^^^^^^^^^^^^^^^^ help: replace with: `counter.value.is_multiple_of(2)`
        |
        = help: for further information visit https://rust-lang.github.io/rust-clippy/rust-1.92.0/index.html#manual_is_multiple_of